id: P009513
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3394
  title: ལེགས་རྩོམ་སྙིང་བསྡུས།
  author: ''
  volumes:
    68af3bfffd2e4693b5eb33601128188c:
      image_group_id: I3CN4259
      title: ''
      volume_number: 1
      total_pages: 380
